// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: corerpc/core.proto

package corerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_OK     ResponseCode = 0
	ResponseCode_FAILED ResponseCode = 1
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	ResponseCode_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_corerpc_core_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_corerpc_core_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{0}
}

type CoreState int32

const (
	CoreState_STOPPED  CoreState = 0
	CoreState_STARTING CoreState = 1
	CoreState_STARTED  CoreState = 2
	CoreState_STOPPING CoreState = 3
)

// Enum value maps for CoreState.
var (
	CoreState_name = map[int32]string{
		0: "STOPPED",
		1: "STARTING",
		2: "STARTED",
		3: "STOPPING",
	}
	CoreState_value = map[string]int32{
		"STOPPED":  0,
		"STARTING": 1,
		"STARTED":  2,
		"STOPPING": 3,
	}
)

func (x CoreState) Enum() *CoreState {
	p := new(CoreState)
	*p = x
	return p
}

func (x CoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_corerpc_core_proto_enumTypes[1].Descriptor()
}

func (CoreState) Type() protoreflect.EnumType {
	return &file_corerpc_core_proto_enumTypes[1]
}

func (x CoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreState.Descriptor instead.
func (CoreState) EnumDescriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_EMPTY                 MessageType = 0
	MessageType_EMPTY_CONFIGURATION   MessageType = 1
	MessageType_START_COMMAND_SERVER  MessageType = 2
	MessageType_CREATE_SERVICE        MessageType = 3
	MessageType_START_SERVICE         MessageType = 4
	MessageType_UNEXPECTED_ERROR      MessageType = 5
	MessageType_ALREADY_STARTED       MessageType = 6
	MessageType_ALREADY_STOPPED       MessageType = 7
	MessageType_INSTANCE_NOT_FOUND    MessageType = 8
	MessageType_INSTANCE_NOT_STOPPED  MessageType = 9
	MessageType_INSTANCE_NOT_STARTED  MessageType = 10
	MessageType_ERROR_BUILDING_CONFIG MessageType = 11
	MessageType_ERROR_PARSING_CONFIG  MessageType = 12
	MessageType_ERROR_READING_CONFIG  MessageType = 13
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "EMPTY",
		1:  "EMPTY_CONFIGURATION",
		2:  "START_COMMAND_SERVER",
		3:  "CREATE_SERVICE",
		4:  "START_SERVICE",
		5:  "UNEXPECTED_ERROR",
		6:  "ALREADY_STARTED",
		7:  "ALREADY_STOPPED",
		8:  "INSTANCE_NOT_FOUND",
		9:  "INSTANCE_NOT_STOPPED",
		10: "INSTANCE_NOT_STARTED",
		11: "ERROR_BUILDING_CONFIG",
		12: "ERROR_PARSING_CONFIG",
		13: "ERROR_READING_CONFIG",
	}
	MessageType_value = map[string]int32{
		"EMPTY":                 0,
		"EMPTY_CONFIGURATION":   1,
		"START_COMMAND_SERVER":  2,
		"CREATE_SERVICE":        3,
		"START_SERVICE":         4,
		"UNEXPECTED_ERROR":      5,
		"ALREADY_STARTED":       6,
		"ALREADY_STOPPED":       7,
		"INSTANCE_NOT_FOUND":    8,
		"INSTANCE_NOT_STOPPED":  9,
		"INSTANCE_NOT_STARTED":  10,
		"ERROR_BUILDING_CONFIG": 11,
		"ERROR_PARSING_CONFIG":  12,
		"ERROR_READING_CONFIG":  13,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_corerpc_core_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_corerpc_core_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{2}
}

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
	LogLevel_FATAL   LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
		4: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"DEBUG":   0,
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
		"FATAL":   4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_corerpc_core_proto_enumTypes[3].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_corerpc_core_proto_enumTypes[3]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{3}
}

type LogType int32

const (
	LogType_CORE    LogType = 0
	LogType_SERVICE LogType = 1
	LogType_CONFIG  LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "CORE",
		1: "SERVICE",
		2: "CONFIG",
	}
	LogType_value = map[string]int32{
		"CORE":    0,
		"SERVICE": 1,
		"CONFIG":  2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_corerpc_core_proto_enumTypes[4].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_corerpc_core_proto_enumTypes[4]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{4}
}

type CoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreState     CoreState              `protobuf:"varint,1,opt,name=core_state,json=coreState,proto3,enum=corerpc.CoreState" json:"core_state,omitempty"`
	MessageType   MessageType            `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=corerpc.MessageType" json:"message_type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInfoResponse) Reset() {
	*x = CoreInfoResponse{}
	mi := &file_corerpc_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInfoResponse) ProtoMessage() {}

func (x *CoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInfoResponse.ProtoReflect.Descriptor instead.
func (*CoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{0}
}

func (x *CoreInfoResponse) GetCoreState() CoreState {
	if x != nil {
		return x.CoreState
	}
	return CoreState_STOPPED
}

func (x *CoreInfoResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_EMPTY
}

func (x *CoreInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath             string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigContent          string                 `protobuf:"bytes,2,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"` // Optional if configPath is not provided.
	DisableMemoryLimit     bool                   `protobuf:"varint,3,opt,name=disable_memory_limit,json=disableMemoryLimit,proto3" json:"disable_memory_limit,omitempty"`
	DelayStart             bool                   `protobuf:"varint,4,opt,name=delay_start,json=delayStart,proto3" json:"delay_start,omitempty"`
	EnableOldCommandServer bool                   `protobuf:"varint,5,opt,name=enable_old_command_server,json=enableOldCommandServer,proto3" json:"enable_old_command_server,omitempty"`
	EnableRawConfig        bool                   `protobuf:"varint,6,opt,name=enable_raw_config,json=enableRawConfig,proto3" json:"enable_raw_config,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_corerpc_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *StartRequest) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *StartRequest) GetDisableMemoryLimit() bool {
	if x != nil {
		return x.DisableMemoryLimit
	}
	return false
}

func (x *StartRequest) GetDelayStart() bool {
	if x != nil {
		return x.DelayStart
	}
	return false
}

func (x *StartRequest) GetEnableOldCommandServer() bool {
	if x != nil {
		return x.EnableOldCommandServer
	}
	return false
}

func (x *StartRequest) GetEnableRawConfig() bool {
	if x != nil {
		return x.EnableRawConfig
	}
	return false
}

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePath      string                 `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	WorkingPath   string                 `protobuf:"bytes,2,opt,name=working_path,json=workingPath,proto3" json:"working_path,omitempty"`
	TempPath      string                 `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_corerpc_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{2}
}

func (x *SetupRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *SetupRequest) GetWorkingPath() string {
	if x != nil {
		return x.WorkingPath
	}
	return ""
}

func (x *SetupRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  ResponseCode           `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=corerpc.ResponseCode" json:"response_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_corerpc_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_corerpc_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{4}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_corerpc_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{5}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_corerpc_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{6}
}

type SystemInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Memory           int64                  `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Goroutines       int32                  `protobuf:"varint,2,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	ConnectionsIn    int32                  `protobuf:"varint,3,opt,name=connections_in,json=connectionsIn,proto3" json:"connections_in,omitempty"`
	ConnectionsOut   int32                  `protobuf:"varint,4,opt,name=connections_out,json=connectionsOut,proto3" json:"connections_out,omitempty"`
	TrafficAvailable bool                   `protobuf:"varint,5,opt,name=traffic_available,json=trafficAvailable,proto3" json:"traffic_available,omitempty"`
	Uplink           int64                  `protobuf:"varint,6,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink         int64                  `protobuf:"varint,7,opt,name=downlink,proto3" json:"downlink,omitempty"`
	UplinkTotal      int64                  `protobuf:"varint,8,opt,name=uplink_total,json=uplinkTotal,proto3" json:"uplink_total,omitempty"`
	DownlinkTotal    int64                  `protobuf:"varint,9,opt,name=downlink_total,json=downlinkTotal,proto3" json:"downlink_total,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_corerpc_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{7}
}

func (x *SystemInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SystemInfo) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *SystemInfo) GetConnectionsIn() int32 {
	if x != nil {
		return x.ConnectionsIn
	}
	return 0
}

func (x *SystemInfo) GetConnectionsOut() int32 {
	if x != nil {
		return x.ConnectionsOut
	}
	return 0
}

func (x *SystemInfo) GetTrafficAvailable() bool {
	if x != nil {
		return x.TrafficAvailable
	}
	return false
}

func (x *SystemInfo) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *SystemInfo) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *SystemInfo) GetUplinkTotal() int64 {
	if x != nil {
		return x.UplinkTotal
	}
	return 0
}

func (x *SystemInfo) GetDownlinkTotal() int64 {
	if x != nil {
		return x.DownlinkTotal
	}
	return 0
}

type OutboundGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UrlTestTime   int64                  `protobuf:"varint,3,opt,name=url_test_time,json=urlTestTime,proto3" json:"url_test_time,omitempty"`
	UrlTestDelay  int32                  `protobuf:"varint,4,opt,name=url_test_delay,json=urlTestDelay,proto3" json:"url_test_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroupItem) Reset() {
	*x = OutboundGroupItem{}
	mi := &file_corerpc_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroupItem) ProtoMessage() {}

func (x *OutboundGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroupItem.ProtoReflect.Descriptor instead.
func (*OutboundGroupItem) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{8}
}

func (x *OutboundGroupItem) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundGroupItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundGroupItem) GetUrlTestTime() int64 {
	if x != nil {
		return x.UrlTestTime
	}
	return 0
}

func (x *OutboundGroupItem) GetUrlTestDelay() int32 {
	if x != nil {
		return x.UrlTestDelay
	}
	return 0
}

type OutboundGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Selected      string                 `protobuf:"bytes,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Items         []*OutboundGroupItem   `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroup) Reset() {
	*x = OutboundGroup{}
	mi := &file_corerpc_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroup) ProtoMessage() {}

func (x *OutboundGroup) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroup.ProtoReflect.Descriptor instead.
func (*OutboundGroup) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{9}
}

func (x *OutboundGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundGroup) GetSelected() string {
	if x != nil {
		return x.Selected
	}
	return ""
}

func (x *OutboundGroup) GetItems() []*OutboundGroupItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OutboundGroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OutboundGroup       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroupList) Reset() {
	*x = OutboundGroupList{}
	mi := &file_corerpc_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroupList) ProtoMessage() {}

func (x *OutboundGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroupList.ProtoReflect.Descriptor instead.
func (*OutboundGroupList) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{10}
}

func (x *OutboundGroupList) GetItems() []*OutboundGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

type WarpAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpAccount) Reset() {
	*x = WarpAccount{}
	mi := &file_corerpc_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpAccount) ProtoMessage() {}

func (x *WarpAccount) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpAccount.ProtoReflect.Descriptor instead.
func (*WarpAccount) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{11}
}

func (x *WarpAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WarpAccount) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type WarpWireguardConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey       string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	LocalAddressIpv4 string                 `protobuf:"bytes,2,opt,name=local_address_ipv4,json=localAddressIpv4,proto3" json:"local_address_ipv4,omitempty"`
	LocalAddressIpv6 string                 `protobuf:"bytes,3,opt,name=local_address_ipv6,json=localAddressIpv6,proto3" json:"local_address_ipv6,omitempty"`
	PeerPublicKey    string                 `protobuf:"bytes,4,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WarpWireguardConfig) Reset() {
	*x = WarpWireguardConfig{}
	mi := &file_corerpc_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpWireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpWireguardConfig) ProtoMessage() {}

func (x *WarpWireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpWireguardConfig.ProtoReflect.Descriptor instead.
func (*WarpWireguardConfig) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{12}
}

func (x *WarpWireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WarpWireguardConfig) GetLocalAddressIpv4() string {
	if x != nil {
		return x.LocalAddressIpv4
	}
	return ""
}

func (x *WarpWireguardConfig) GetLocalAddressIpv6() string {
	if x != nil {
		return x.LocalAddressIpv6
	}
	return ""
}

func (x *WarpWireguardConfig) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *WarpWireguardConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SystemProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProxyStatus) Reset() {
	*x = SystemProxyStatus{}
	mi := &file_corerpc_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProxyStatus) ProtoMessage() {}

func (x *SystemProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProxyStatus.ProtoReflect.Descriptor instead.
func (*SystemProxyStatus) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{13}
}

func (x *SystemProxyStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SystemProxyStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SelectOutboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupTag      string                 `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	OutboundTag   string                 `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOutboundRequest) Reset() {
	*x = SelectOutboundRequest{}
	mi := &file_corerpc_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOutboundRequest) ProtoMessage() {}

func (x *SelectOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOutboundRequest.ProtoReflect.Descriptor instead.
func (*SelectOutboundRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{14}
}

func (x *SelectOutboundRequest) GetGroupTag() string {
	if x != nil {
		return x.GroupTag
	}
	return ""
}

func (x *SelectOutboundRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

type UrlTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupTag      string                 `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlTestRequest) Reset() {
	*x = UrlTestRequest{}
	mi := &file_corerpc_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlTestRequest) ProtoMessage() {}

func (x *UrlTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlTestRequest.ProtoReflect.Descriptor instead.
func (*UrlTestRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{15}
}

func (x *UrlTestRequest) GetGroupTag() string {
	if x != nil {
		return x.GroupTag
	}
	return ""
}

type SetSystemProxyEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSystemProxyEnabledRequest) Reset() {
	*x = SetSystemProxyEnabledRequest{}
	mi := &file_corerpc_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSystemProxyEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSystemProxyEnabledRequest) ProtoMessage() {}

func (x *SetSystemProxyEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSystemProxyEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetSystemProxyEnabledRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{16}
}

func (x *SetSystemProxyEnabledRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=corerpc.LogLevel" json:"level,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=corerpc.LogType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_corerpc_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{17}
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogMessage) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_CORE
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_corerpc_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{18}
}

type TunnelStartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ipv6                   bool                   `protobuf:"varint,1,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	ServerPort             int32                  `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	StrictRoute            bool                   `protobuf:"varint,3,opt,name=strict_route,json=strictRoute,proto3" json:"strict_route,omitempty"`
	EndpointIndependentNat bool                   `protobuf:"varint,4,opt,name=endpoint_independent_nat,json=endpointIndependentNat,proto3" json:"endpoint_independent_nat,omitempty"`
	Stack                  string                 `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TunnelStartRequest) Reset() {
	*x = TunnelStartRequest{}
	mi := &file_corerpc_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStartRequest) ProtoMessage() {}

func (x *TunnelStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStartRequest.ProtoReflect.Descriptor instead.
func (*TunnelStartRequest) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{19}
}

func (x *TunnelStartRequest) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *TunnelStartRequest) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *TunnelStartRequest) GetStrictRoute() bool {
	if x != nil {
		return x.StrictRoute
	}
	return false
}

func (x *TunnelStartRequest) GetEndpointIndependentNat() bool {
	if x != nil {
		return x.EndpointIndependentNat
	}
	return false
}

func (x *TunnelStartRequest) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type TunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelResponse) Reset() {
	*x = TunnelResponse{}
	mi := &file_corerpc_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse) ProtoMessage() {}

func (x *TunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corerpc_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse.ProtoReflect.Descriptor instead.
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return file_corerpc_core_proto_rawDescGZIP(), []int{20}
}

func (x *TunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_corerpc_core_proto protoreflect.FileDescriptor

const file_corerpc_core_proto_rawDesc = "" +
	"\n" +
	"\x12corerpc/core.proto\x12\acorerpc\"\x98\x01\n" +
	"\x10CoreInfoResponse\x121\n" +
	"\n" +
	"core_state\x18\x01 \x01(\x0e2\x12.corerpc.CoreStateR\tcoreState\x127\n" +
	"\fmessage_type\x18\x02 \x01(\x0e2\x14.corerpc.MessageTypeR\vmessageType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x02\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12%\n" +
	"\x0econfig_content\x18\x02 \x01(\tR\rconfigContent\x120\n" +
	"\x14disable_memory_limit\x18\x03 \x01(\bR\x12disableMemoryLimit\x12\x1f\n" +
	"\vdelay_start\x18\x04 \x01(\bR\n" +
	"delayStart\x129\n" +
	"\x19enable_old_command_server\x18\x05 \x01(\bR\x16enableOldCommandServer\x12*\n" +
	"\x11enable_raw_config\x18\x06 \x01(\bR\x0fenableRawConfig\"k\n" +
	"\fSetupRequest\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\x12!\n" +
	"\fworking_path\x18\x02 \x01(\tR\vworkingPath\x12\x1b\n" +
	"\ttemp_path\x18\x03 \x01(\tR\btempPath\"`\n" +
	"\bResponse\x12:\n" +
	"\rresponse_code\x18\x01 \x01(\x0e2\x15.corerpc.ResponseCodeR\fresponseCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"\xbf\x02\n" +
	"\n" +
	"SystemInfo\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x02 \x01(\x05R\n" +
	"goroutines\x12%\n" +
	"\x0econnections_in\x18\x03 \x01(\x05R\rconnectionsIn\x12'\n" +
	"\x0fconnections_out\x18\x04 \x01(\x05R\x0econnectionsOut\x12+\n" +
	"\x11traffic_available\x18\x05 \x01(\bR\x10trafficAvailable\x12\x16\n" +
	"\x06uplink\x18\x06 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\a \x01(\x03R\bdownlink\x12!\n" +
	"\fuplink_total\x18\b \x01(\x03R\vuplinkTotal\x12%\n" +
	"\x0edownlink_total\x18\t \x01(\x03R\rdownlinkTotal\"\x83\x01\n" +
	"\x11OutboundGroupItem\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\rurl_test_time\x18\x03 \x01(\x03R\vurlTestTime\x12$\n" +
	"\x0eurl_test_delay\x18\x04 \x01(\x05R\furlTestDelay\"\x83\x01\n" +
	"\rOutboundGroup\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\tR\bselected\x120\n" +
	"\x05items\x18\x04 \x03(\v2\x1a.corerpc.OutboundGroupItemR\x05items\"A\n" +
	"\x11OutboundGroupList\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.corerpc.OutboundGroupR\x05items\"O\n" +
	"\vWarpAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\xd7\x01\n" +
	"\x13WarpWireguardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12,\n" +
	"\x12local_address_ipv4\x18\x02 \x01(\tR\x10localAddressIpv4\x12,\n" +
	"\x12local_address_ipv6\x18\x03 \x01(\tR\x10localAddressIpv6\x12&\n" +
	"\x0fpeer_public_key\x18\x04 \x01(\tR\rpeerPublicKey\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\"K\n" +
	"\x11SystemProxyStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"W\n" +
	"\x15SelectOutboundRequest\x12\x1b\n" +
	"\tgroup_tag\x18\x01 \x01(\tR\bgroupTag\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\"-\n" +
	"\x0eUrlTestRequest\x12\x1b\n" +
	"\tgroup_tag\x18\x01 \x01(\tR\bgroupTag\"=\n" +
	"\x1cSetSystemProxyEnabledRequest\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x01 \x01(\bR\tisEnabled\"u\n" +
	"\n" +
	"LogMessage\x12'\n" +
	"\x05level\x18\x01 \x01(\x0e2\x11.corerpc.LogLevelR\x05level\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.corerpc.LogTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\r\n" +
	"\vStopRequest\"\xbc\x01\n" +
	"\x12TunnelStartRequest\x12\x12\n" +
	"\x04ipv6\x18\x01 \x01(\bR\x04ipv6\x12\x1f\n" +
	"\vserver_port\x18\x02 \x01(\x05R\n" +
	"serverPort\x12!\n" +
	"\fstrict_route\x18\x03 \x01(\bR\vstrictRoute\x128\n" +
	"\x18endpoint_independent_nat\x18\x04 \x01(\bR\x16endpointIndependentNat\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\tR\x05stack\"*\n" +
	"\x0eTunnelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\"\n" +
	"\fResponseCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01*A\n" +
	"\tCoreState\x12\v\n" +
	"\aSTOPPED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\v\n" +
	"\aSTARTED\x10\x02\x12\f\n" +
	"\bSTOPPING\x10\x03*\xcd\x02\n" +
	"\vMessageType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x17\n" +
	"\x13EMPTY_CONFIGURATION\x10\x01\x12\x18\n" +
	"\x14START_COMMAND_SERVER\x10\x02\x12\x12\n" +
	"\x0eCREATE_SERVICE\x10\x03\x12\x11\n" +
	"\rSTART_SERVICE\x10\x04\x12\x14\n" +
	"\x10UNEXPECTED_ERROR\x10\x05\x12\x13\n" +
	"\x0fALREADY_STARTED\x10\x06\x12\x13\n" +
	"\x0fALREADY_STOPPED\x10\a\x12\x16\n" +
	"\x12INSTANCE_NOT_FOUND\x10\b\x12\x18\n" +
	"\x14INSTANCE_NOT_STOPPED\x10\t\x12\x18\n" +
	"\x14INSTANCE_NOT_STARTED\x10\n" +
	"\x12\x19\n" +
	"\x15ERROR_BUILDING_CONFIG\x10\v\x12\x18\n" +
	"\x14ERROR_PARSING_CONFIG\x10\f\x12\x18\n" +
	"\x14ERROR_READING_CONFIG\x10\r*B\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\t\n" +
	"\x05FATAL\x10\x04*,\n" +
	"\aLogType\x12\b\n" +
	"\x04CORE\x10\x00\x12\v\n" +
	"\aSERVICE\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x022\x87\x01\n" +
	"\x05Hello\x129\n" +
	"\bSayHello\x12\x15.corerpc.HelloRequest\x1a\x16.corerpc.HelloResponse\x12C\n" +
	"\x0eSayHelloStream\x12\x15.corerpc.HelloRequest\x1a\x16.corerpc.HelloResponse(\x010\x012\x92\a\n" +
	"\x04Core\x129\n" +
	"\x05Start\x12\x15.corerpc.StartRequest\x1a\x19.corerpc.CoreInfoResponse\x12G\n" +
	"\x10CoreInfoListener\x12\x14.corerpc.StopRequest\x1a\x19.corerpc.CoreInfoResponse(\x010\x01\x12E\n" +
	"\rOutboundsInfo\x12\x14.corerpc.StopRequest\x1a\x1a.corerpc.OutboundGroupList(\x010\x01\x12I\n" +
	"\x11MainOutboundsInfo\x12\x14.corerpc.StopRequest\x1a\x1a.corerpc.OutboundGroupList(\x010\x01\x12>\n" +
	"\rGetSystemInfo\x12\x14.corerpc.StopRequest\x1a\x13.corerpc.SystemInfo(\x010\x01\x121\n" +
	"\x05Setup\x12\x15.corerpc.SetupRequest\x1a\x11.corerpc.Response\x12@\n" +
	"\fStartService\x12\x15.corerpc.StartRequest\x1a\x19.corerpc.CoreInfoResponse\x121\n" +
	"\x04Stop\x12\x0e.corerpc.Empty\x1a\x19.corerpc.CoreInfoResponse\x12;\n" +
	"\aRestart\x12\x15.corerpc.StartRequest\x1a\x19.corerpc.CoreInfoResponse\x12C\n" +
	"\x0eSelectOutbound\x12\x1e.corerpc.SelectOutboundRequest\x1a\x11.corerpc.Response\x125\n" +
	"\aUrlTest\x12\x17.corerpc.UrlTestRequest\x1a\x11.corerpc.Response\x12B\n" +
	"\x14GetSystemProxyStatus\x12\x0e.corerpc.Empty\x1a\x1a.corerpc.SystemProxyStatus\x12Q\n" +
	"\x15SetSystemProxyEnabled\x12%.corerpc.SetSystemProxyEnabledRequest\x1a\x11.corerpc.Response\x12<\n" +
	"\vLogListener\x12\x14.corerpc.StopRequest\x1a\x13.corerpc.LogMessage(\x010\x012\xe3\x01\n" +
	"\rTunnelService\x12=\n" +
	"\x05Start\x12\x1b.corerpc.TunnelStartRequest\x1a\x17.corerpc.TunnelResponse\x12/\n" +
	"\x04Stop\x12\x0e.corerpc.Empty\x1a\x17.corerpc.TunnelResponse\x121\n" +
	"\x06Status\x12\x0e.corerpc.Empty\x1a\x17.corerpc.TunnelResponse\x12/\n" +
	"\x04Exit\x12\x0e.corerpc.Empty\x1a\x17.corerpc.TunnelResponseB\vZ\t./corerpcb\x06proto3"

var (
	file_corerpc_core_proto_rawDescOnce sync.Once
	file_corerpc_core_proto_rawDescData []byte
)

func file_corerpc_core_proto_rawDescGZIP() []byte {
	file_corerpc_core_proto_rawDescOnce.Do(func() {
		file_corerpc_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corerpc_core_proto_rawDesc), len(file_corerpc_core_proto_rawDesc)))
	})
	return file_corerpc_core_proto_rawDescData
}

var file_corerpc_core_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_corerpc_core_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_corerpc_core_proto_goTypes = []any{
	(ResponseCode)(0),                    // 0: corerpc.ResponseCode
	(CoreState)(0),                       // 1: corerpc.CoreState
	(MessageType)(0),                     // 2: corerpc.MessageType
	(LogLevel)(0),                        // 3: corerpc.LogLevel
	(LogType)(0),                         // 4: corerpc.LogType
	(*CoreInfoResponse)(nil),             // 5: corerpc.CoreInfoResponse
	(*StartRequest)(nil),                 // 6: corerpc.StartRequest
	(*SetupRequest)(nil),                 // 7: corerpc.SetupRequest
	(*Response)(nil),                     // 8: corerpc.Response
	(*HelloRequest)(nil),                 // 9: corerpc.HelloRequest
	(*HelloResponse)(nil),                // 10: corerpc.HelloResponse
	(*Empty)(nil),                        // 11: corerpc.Empty
	(*SystemInfo)(nil),                   // 12: corerpc.SystemInfo
	(*OutboundGroupItem)(nil),            // 13: corerpc.OutboundGroupItem
	(*OutboundGroup)(nil),                // 14: corerpc.OutboundGroup
	(*OutboundGroupList)(nil),            // 15: corerpc.OutboundGroupList
	(*WarpAccount)(nil),                  // 16: corerpc.WarpAccount
	(*WarpWireguardConfig)(nil),          // 17: corerpc.WarpWireguardConfig
	(*SystemProxyStatus)(nil),            // 18: corerpc.SystemProxyStatus
	(*SelectOutboundRequest)(nil),        // 19: corerpc.SelectOutboundRequest
	(*UrlTestRequest)(nil),               // 20: corerpc.UrlTestRequest
	(*SetSystemProxyEnabledRequest)(nil), // 21: corerpc.SetSystemProxyEnabledRequest
	(*LogMessage)(nil),                   // 22: corerpc.LogMessage
	(*StopRequest)(nil),                  // 23: corerpc.StopRequest
	(*TunnelStartRequest)(nil),           // 24: corerpc.TunnelStartRequest
	(*TunnelResponse)(nil),               // 25: corerpc.TunnelResponse
}
var file_corerpc_core_proto_depIdxs = []int32{
	1,  // 0: corerpc.CoreInfoResponse.core_state:type_name -> corerpc.CoreState
	2,  // 1: corerpc.CoreInfoResponse.message_type:type_name -> corerpc.MessageType
	0,  // 2: corerpc.Response.response_code:type_name -> corerpc.ResponseCode
	13, // 3: corerpc.OutboundGroup.items:type_name -> corerpc.OutboundGroupItem
	14, // 4: corerpc.OutboundGroupList.items:type_name -> corerpc.OutboundGroup
	3,  // 5: corerpc.LogMessage.level:type_name -> corerpc.LogLevel
	4,  // 6: corerpc.LogMessage.type:type_name -> corerpc.LogType
	9,  // 7: corerpc.Hello.SayHello:input_type -> corerpc.HelloRequest
	9,  // 8: corerpc.Hello.SayHelloStream:input_type -> corerpc.HelloRequest
	6,  // 9: corerpc.Core.Start:input_type -> corerpc.StartRequest
	23, // 10: corerpc.Core.CoreInfoListener:input_type -> corerpc.StopRequest
	23, // 11: corerpc.Core.OutboundsInfo:input_type -> corerpc.StopRequest
	23, // 12: corerpc.Core.MainOutboundsInfo:input_type -> corerpc.StopRequest
	23, // 13: corerpc.Core.GetSystemInfo:input_type -> corerpc.StopRequest
	7,  // 14: corerpc.Core.Setup:input_type -> corerpc.SetupRequest
	6,  // 15: corerpc.Core.StartService:input_type -> corerpc.StartRequest
	11, // 16: corerpc.Core.Stop:input_type -> corerpc.Empty
	6,  // 17: corerpc.Core.Restart:input_type -> corerpc.StartRequest
	19, // 18: corerpc.Core.SelectOutbound:input_type -> corerpc.SelectOutboundRequest
	20, // 19: corerpc.Core.UrlTest:input_type -> corerpc.UrlTestRequest
	11, // 20: corerpc.Core.GetSystemProxyStatus:input_type -> corerpc.Empty
	21, // 21: corerpc.Core.SetSystemProxyEnabled:input_type -> corerpc.SetSystemProxyEnabledRequest
	23, // 22: corerpc.Core.LogListener:input_type -> corerpc.StopRequest
	24, // 23: corerpc.TunnelService.Start:input_type -> corerpc.TunnelStartRequest
	11, // 24: corerpc.TunnelService.Stop:input_type -> corerpc.Empty
	11, // 25: corerpc.TunnelService.Status:input_type -> corerpc.Empty
	11, // 26: corerpc.TunnelService.Exit:input_type -> corerpc.Empty
	10, // 27: corerpc.Hello.SayHello:output_type -> corerpc.HelloResponse
	10, // 28: corerpc.Hello.SayHelloStream:output_type -> corerpc.HelloResponse
	5,  // 29: corerpc.Core.Start:output_type -> corerpc.CoreInfoResponse
	5,  // 30: corerpc.Core.CoreInfoListener:output_type -> corerpc.CoreInfoResponse
	15, // 31: corerpc.Core.OutboundsInfo:output_type -> corerpc.OutboundGroupList
	15, // 32: corerpc.Core.MainOutboundsInfo:output_type -> corerpc.OutboundGroupList
	12, // 33: corerpc.Core.GetSystemInfo:output_type -> corerpc.SystemInfo
	8,  // 34: corerpc.Core.Setup:output_type -> corerpc.Response
	5,  // 35: corerpc.Core.StartService:output_type -> corerpc.CoreInfoResponse
	5,  // 36: corerpc.Core.Stop:output_type -> corerpc.CoreInfoResponse
	5,  // 37: corerpc.Core.Restart:output_type -> corerpc.CoreInfoResponse
	8,  // 38: corerpc.Core.SelectOutbound:output_type -> corerpc.Response
	8,  // 39: corerpc.Core.UrlTest:output_type -> corerpc.Response
	18, // 40: corerpc.Core.GetSystemProxyStatus:output_type -> corerpc.SystemProxyStatus
	8,  // 41: corerpc.Core.SetSystemProxyEnabled:output_type -> corerpc.Response
	22, // 42: corerpc.Core.LogListener:output_type -> corerpc.LogMessage
	25, // 43: corerpc.TunnelService.Start:output_type -> corerpc.TunnelResponse
	25, // 44: corerpc.TunnelService.Stop:output_type -> corerpc.TunnelResponse
	25, // 45: corerpc.TunnelService.Status:output_type -> corerpc.TunnelResponse
	25, // 46: corerpc.TunnelService.Exit:output_type -> corerpc.TunnelResponse
	27, // [27:47] is the sub-list for method output_type
	7,  // [7:27] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_corerpc_core_proto_init() }
func file_corerpc_core_proto_init() {
	if File_corerpc_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corerpc_core_proto_rawDesc), len(file_corerpc_core_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_corerpc_core_proto_goTypes,
		DependencyIndexes: file_corerpc_core_proto_depIdxs,
		EnumInfos:         file_corerpc_core_proto_enumTypes,
		MessageInfos:      file_corerpc_core_proto_msgTypes,
	}.Build()
	File_corerpc_core_proto = out.File
	file_corerpc_core_proto_goTypes = nil
	file_corerpc_core_proto_depIdxs = nil
}
