name: Build

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      is-release:
        type: boolean
        default: false

jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              name: "tunnel-core-android",
              os: "ubuntu-latest",
              target: "android",
            }
          - {
              name: "tunnel-core-linux-amd64",
              os: "ubuntu-latest",
              target: "linux-amd64",
            }
          - {
              name: "tunnel-core-windows-amd64",
              os: "ubuntu-latest",
              target: "windows-amd64",
              aarch: "x64",
            }
          - {
              name: "tunnel-core-macos-universal",
              os: "macos-15",
              target: "macos-universal",
            }
          - { name: "tunnel-core-ios", os: "macos-15", target: "ios" }

    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: false

      - name: Patch module
        run: |
          bash patch-module.sh

      - name: Setup Java
        if: startsWith(matrix.job.target,'android')
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup NDK
        if: startsWith(matrix.job.target,'android')
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
          add-to-path: true
          local-cache: false
          link-to-sdk: true

      - name: Setup MinGW
        if: startsWith(matrix.job.target,'windows')
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.job.aarch }}

      - name: Setup macos
        if: startsWith(matrix.job.target,'macos') || startsWith(matrix.job.target,'ios')
        run: |
          brew install create-dmg tree coreutils

      - name: Build
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          if [[ "${{ matrix.job.target }}" == "android" ]]; then
            export CGO_CFLAGS="-I${ANDROID_NDK_HOME}/sources/android/cpufeatures"
          fi
          make -j$(($(nproc) + 1)) ${{ matrix.job.target }}

      - name: zip
        working-directory: bin
        run: |
          tree
          rm -f /*.h */*.h
          files=$(find . -maxdepth 2 \( \
            -name "libcore.dll" \
            -o -name "libcronet.dll" \
            -o -name "libcronet.so" \
            -o -name "libcore.so" \
            -o -name "libcore.dylib" \
            -o -name "libcore-amd64.dylib" \
            -o -name "libcore-arm64.dylib" \
            -o -name "libcore.aar" \
            -o -name "Libcore.xcframework" \
            -o -name "lib" \
          \))
          echo tar -czvf ${{ matrix.job.name }}.tar.gz $files
          tar -czvf ${{ matrix.job.name }}.tar.gz $files

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload-artifact && success() }}
        with:
          name: ${{ matrix.job.name }}
          path: bin/*.tar.gz
          retention-days: 1

  upload-prerelease:
    permissions: write-all
    if: ${{ inputs.upload-artifact && !inputs.is-release }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: tunnel-*
          path: bin/

      - name: Display Files Structure
        run: tree
        working-directory: bin

      - name: Delete Current Release Assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "draft"
          deleteOnlyFromDrafts: false

      - name: Create or Update Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./bin/*.tar.gz
          name: "draft"
          tag_name: "draft"
          prerelease: true

  upload-release:
    permissions: write-all
    if: ${{ inputs.is-release }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: tunnel-*
          path: bin/

      - name: Display Files Structure
        run: ls -R
        working-directory: bin

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag-name }}
          files: bin/*.tar.gz

  delete-artifact:
    runs-on: ubuntu-latest
    needs: [upload-prerelease, upload-release]
    if: |
      always() &&
      (
        needs.upload-prerelease.result == 'success' ||
        needs.upload-release.result == 'success'
      )
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            tunnel-*
