name: CI

on:
  push:
    branches:
      - main
      - dev
      - ios
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      upload-artifact: true
      tag-name: "draft"
      is-release: false
